name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^9.0.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  http: ^1.6.0
  image_picker: ^1.2.1
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.14+3
  google_maps_flutter: ^2.14.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  shimmer_animation: ^2.2.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  url_strategy: ^0.3.0
  universal_html: ^2.3.0
  image: ^4.5.4
  flutter_widget_from_html_core: ^0.17.0
  country_code_picker: ^3.4.1
  flutter_typeahead: ^5.2.0
  circular_countdown_timer: ^0.2.4
#  timezone: ^0.10.1
  marquee: ^2.3.0
  flutter_inappwebview: ^6.1.5
  audioplayers: ^6.5.1
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^7.2.0
  dotted_border: ^3.1.0
  share_plus: ^12.0.1
  expandable_bottom_sheet: ^1.1.1+1
  scroll_to_index: ^3.0.1
#  google_maps_webservice: ^0.0.19
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  just_the_tooltip: ^0.0.12
  sign_in_with_apple: ^7.0.1
  mobile_scanner: ^7.1.3
  app_links: ^7.0.0
  go_router: ^17.0.0
  firebase_auth: ^6.1.2
  flutter_svg: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^6.0.2
  animated_custom_dropdown: ^3.1.1
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.1.1
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  dotted_line: ^3.2.3
#  cached_network_image_platform_interface:
  collection: any
  app_tracking_transparency: ^2.0.6+1
  skeletonizer: ^2.1.1


dev_dependencies:
  flutter_lints: ^6.0.0
  fwfh_text_style: ^2.23.8
  drift_dev: ^2.29.0
  build_runner: ^2.10.3

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/json/
    - assets/payment/
    - assets/
    - web/assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400